eureka:
  client:
    fetch-registry: true
    registry-with-eureka: true
  instance:
    prefer-ip-address: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
      
